### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by lmacuisdean** [aneaville/MMM-GooglePhotos#122]
Tried installing this module this evening only to be met with the following. Please advise:

"npm WARN deprecated axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 203 packages from 140 contributors and audited 203 packages in 18.826s

6 packages are looking for funding
  run `npm fund` for details

found 12 vulnerabilities (6 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details"

**Comment by Fhealz** [comment]
I'm also getting the same issues

**Comment by hermanho** [comment]
The dependencies are updated in the latest version. Please pull the source code and try it. When the problem is still there, please open a new issue.
