### ISSUE TITLE
Position and size of the photos

### ISSUE THREAD

**Issue by 1Cedric1** [aneaville/MMM-GooglePhotos#131]
![image calendrier](https://user-images.githubusercontent.com/61581150/151649658-055ea91a-822f-4024-9af4-8ba84e34c5de.jpeg)

Dears,

Thank you very much and congratulation for the photo module you provide. It's a pleasure to be able to use it.

I encounter a problem with the position of the photo, placed in the "middle_center" position.

With the standard configuration I have (see attached), the picture is not centered on the screen.
Do you know how it is possible to center it?

![code_photo_miroir](https://user-images.githubusercontent.com/61581150/151649765-c4398bc2-703a-4413-91ed-f9cb260db10e.jpeg)

And is it possible to reduce the dimensions (not the resolution) or the photo on the screen, so that it takes less place an not "touch" the other modules?

Thank you very much in advance for your help.

**Comment by JanTanja** [comment]
Having the same issue
