### ISSUE TITLE
Problems with Token Generation

### ISSUE THREAD

**Issue by mbosselle** [aneaville/MMM-GooglePhotos#133]
Hello,

I am having an odd issue with the command "node generation_token.js:

I run the command, it will take me to the link where I can click though to get the code to past into the command line. then I get TypeError: invalid options argument.

code below

`pi@raspberrypi:~/MagicMirror/modules/MMM-GooglePhotos $ node generate_token.js
[GPHOTOS:AUTH] Opening OAuth URL.

https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary.sharing&response_type=code&client_id=1077221266376-rossho7jqiiepap9ofntu193p37o5d3a.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob

Return here with your code.
> Paste your code: 4/1AX4XfWhFjmbNn4Bin8ygDaEPuZbZHBXPlKH17io3NXVnCBxoGVGO5aP8VQg
/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/mkdirp/lib/opts-arg.js:13
    throw new TypeError('invalid options argument')
          ^

TypeError: invalid options argument
    at optsArg (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/mkdirp/lib/opts-arg.js:13:11)
    at mkdirp (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/mkdirp/index.js:11:10)
    at /home/pi/MagicMirror/modules/MMM-GooglePhotos/GPhotos.js:49:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

Thanks for your help

**Comment by eouia** [comment]
Recently Google seems it might have changed its OAuth2 policy. I have no idea how to solve it at this moment.  
Maybe the verification of the app is a solution, but I hadn't. Usually, MagicMirror is hosted by localhost, so it could not be verified from Google unless it has public domain.

**Comment by hermanho** [comment]
The token generation is changed in latest version. Please pull the source code and try it. When the problem is still there, please open a new issue.
