### ISSUE TITLE
Photos don't refresh from Google albums and im getting an Uncaught RefrenceError on the Moment package

### ISSUE THREAD

**Issue by JustinBa** [aneaville/MMM-GooglePhotos#141]
Hello, I have most things going great for me, however im finding that albums will not refresh unless you reboot the machine (or the js stack).

I have triple checked my auth code and album name settings, and it does work on reset, but when it tries to refresh live I just get the error "Uncought RefrenceError: moment is not defined" on MMM-GooglePhotos.js line 156

I have triple checked that moment is available in the MM node_modules folder, the MMM Google Photos node_modules folder, and the /usr/bin node modules folder, and that they are the correct version, but still not having any luck.

I tried to add an import statement, but JS is not my specialty and it seems like that's not quite the answer. It did not get me anywhere.

Any ideas on what I might be having troubles with?

I am doing this on Debian with the X11 DE on a BeagleBone Black due to the current PI shortage (:/)

**Comment by hermanho** [comment]
Please try with the latest version to see if it has the same problem.
