### ISSUE TITLE
Alternative for Google OAuth out-of-band flow 

### ISSUE THREAD

**Issue by overcast7** [aneaville/MMM-GooglePhotos#145]
As of October 3rd, MMM-Google Photos will probably be no longer working due to Google blocking OOB requests.

Are there any alternatives in the pipeline?

**Comment by jcmarinn** [comment]
+1 to this query

I just received notification from my Google Developer account notifying the OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022

**Comment by overcast37** [comment]
Appreciate the participation.
I would really love to keep this module alive since it's the main thing my MM displays.

Open for solutions or even alternatives

**Comment by aaron-salamanca** [comment]
just wanted to see if anyone has made any progress with this. October is approaching.

**Comment by hermanho** [comment]
I am testing with a Desktop app type, not sure if it can work when the app refresh the offline token. Here is the way:

1. **backup** the existing files `token.json`, `credentials.json` on your target device
2. follow the steps 1-8 in 'Get token.json' in readme and select the Application type as 'Desktop app'
3. clone the repo in your local pc when there is no browser on your target device (rpi4)
4. copy the following file to local source directory
https://github.com/hermanho/MMM-GooglePhotos/blob/fix/google-oauth2/generate_token_v2.js
5. npm install `@google-cloud/local-auth`
```npm i @google-cloud/local-auth```
6. execute the file in your local pc / target device 
`node generate_token_v2.js`
7. A browser should be opened and redirect to Google authentication web page
8. Authorize it and close the browser
9. copy the file `token.json` to target device when you are execute in local pc

**Comment by aaron-salamanca** [comment]
Hello @hermanho. How's the testing going with the desktop app type?

**Comment by hermanho** [comment]
Hi @aaron-salamanca, it looks great. Token can be refreshed every hour in the logging.

**Comment by orayoflighto** [comment]
@hermanho tested with V2.20 and your V2 token worked great. Thanks for all the work.

**Comment by sdetweil** [comment]
@hermanho you should make a pull request.. at least then we can get the whole repo with your change
or at least your fork..

**Comment by vjgn** [comment]
@hermanho thank you for the solution

**Comment by aaron-salamanca** [comment]
has this been merged with the master branch??

**Comment by sdetweil** [comment]
@aaron-salamanca no. see the list of PRs above

and don't hold your breath. last code update was 2 years ago.

you can pull the PR version  instead of the base

**Comment by aaron-salamanca** [comment]
@aneaville coming in hot. 👍 Thanks for merging this!!!

**Comment by BlackiSchwarz** [comment]
Hey,

I am still quite a newbie on Git and MM.
I don't quite understand what to do.
I want to upload pictures from my MM on a RaspberryPi 4 to GooglePhotos. I have created and downloaded the credentials.json.

What do i have to do next?
