### ISSUE TITLE
Photos loading into mirror but not being displayed.

### ISSUE THREAD

**Issue by christilton** [aneaville/MMM-GooglePhotos#153]
Hi All, 

I'm getting this error in the dev tools when I try to run MMM-GooglePhotos. Any ideas?

![image](https://user-images.githubusercontent.com/84406266/208550683-e84ebd45-e513-403f-9310-9d85db2421bf.png)

**Comment by christilton** [comment]
The photos are able to be found in Sources in dev tools but are not displayed to the mirror.

**Comment by danielXengines** [comment]
Hello, 

Are you using the position "middle_third"? If so, please try using a different position. 

Kind regards,
Daniel
