### ISSUE TITLE
Token Generation error using generate_token_v2.js

### ISSUE THREAD

**Issue by mistrysiddh** [aneaville/MMM-GooglePhotos#165]
# Step 01:
cd ~/MagicMirror/modules/
git clone https://github.com/eouia/MMM-GooglePhotos.git
cd MMM-GooglePhotos
npm install

# Step 2
Downloading `credentials.json` from [Google API Console](https://console.developers.google.com/)

# Step 3
generating token using `node generate_token_v2.js`

# Error
```bash
*[master][~/MagicMirror/modules/MMM-GooglePhotos]$ node generate_token_v2.js
node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-GooglePhotos/credentials.json'
Require stack:
- /home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/@google-cloud/local-auth/build/src/index.js
- /home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token_v2.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at authenticate (/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/@google-cloud/local-auth/build/src/index.js:48:21)
    at generate (/home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token_v2.js:13:24)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token_v2.js:27:1)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-GooglePhotos/node_modules/@google-cloud/local-auth/build/src/index.js',
    '/home/pi/MagicMirror/modules/MMM-GooglePhotos/generate_token_v2.js'
  ]
}
```

**Comment by hermanho** [comment]
Have you tried with the steps?

https://github.com/hermanho/MMM-GooglePhotos#get-tokenjson
> 9. Then, you can download your credential json file from list. Downloaded file name would be client_secret_xxxx...xxx.json. rename it as credentials.json and save it to your MMM-GooglePhotos directory.

**Comment by werox709** [comment]
I have the same problem were you able to solve it?
I am running magic mirror on a docker container btw.

**Comment by hermanho** [comment]
> I have the same problem were you able to solve it?
> 
> I am running magic mirror on a docker container btw. 

Is the file credentials.json saved in the same directory in MMM-GooglePhotos inside the container?

**Comment by mistrysiddh** [comment]
> > I have the same problem were you able to solve it?
> > 
> > I am running magic mirror on a docker container btw. 
> 
> Is the file credentials.json saved in the same directory in MMM-GooglePhotos inside the container?

im not using docker container but I have placed the file in the same directory

**Comment by hermanho** [comment]
> > > I have the same problem were you able to solve it?
> > > I am running magic mirror on a docker container btw.
> > 
> > 
> > Is the file credentials.json saved in the same directory in MMM-GooglePhotos inside the container?
> 
> im not using docker container but I have placed the file in the same directory

1. What is your Node.js version?
2. Could you please pull the 'dev' branch and run the command `node generate_token_v2.js` ?
