### ISSUE TITLE
Problem when moving to "previous" picture...

### ISSUE THREAD

**Issue by Snille** [aneaville/MMM-GooglePhotos#170]
Hi! Thank you for this Module! :)
It made it possible for my mirror to double as a "Photo frame" at the same time as being the MM. :)

Here is the problem:
I'm using HA (Node Red) to send notifications to the mirror for control, when moving "forward" in the picture queue it works, but when moving backwards it "stop" at random intervals. It does not "sick" at the same picture all the time...

So, here is the test setup.
I setup a specific Album (MM-Test) added 10 pictures (numbers) and recorded the "forward" and "backwards" clicks... 
Here is the "clip"... Not sure what's going on or if it helps... :)

https://github.com/hermanho/MMM-GooglePhotos/assets/1011699/d733b238-f322-4461-b1a7-0bf7fdc1f23c

Let me know if you need anything else or what I'm doing wrong... :)
Thank you!

Best regards Erik

**Comment by hermanho** [comment]
Hi Erik, could you please try branch https://github.com/hermanho/MMM-GooglePhotos/tree/fix/170 to see if it is working as expected?

**Comment by Snille** [comment]
Morning! Looks like its working! :) At least with the 10 pictures in the test album. :)

Another thing I'm noticing now is the the "fade" only happens when the picture shows, not when it's going away... It fades in but not out... But maybe that's in my end? 

Anyway thank you! :)

**Comment by hermanho** [comment]
Not sure, I would take time to diagnostic the face out. Let me release the fixing for backwards first.

**Comment by Snille** [comment]
Previous picture is now working. :) Thank you!
