### ISSUE TITLE
Ratios not respecting commands

### ISSUE THREAD

**Issue by samuelskeirik** [aneaville/MMM-GooglePhotos#178]
The values for minWHRatio & maxWHRatio dont seem to do what's advertised in the instructions. I'm trying to get landscape only photos.

I've changed both the two above, and fiddled with the show height/width.

# Config File

	{
			module: "MMM-GooglePhotos", 
			position: "fullscreen_below",
			config: {
				  albums: ["MagicMirror"], // Set your album name. like ["My wedding", "family share", "Travle to Paris"]
				  updateInterval: 1000 * 60, // minimum 10 seconds.
				  sort: "random", // "old", "random"
				  uploadAlbum: null, // Only album created by `create_uploadable_album.js`.
				  condition: {
					  fromDate: null, // Or "2018-03", RFC ... format available
					  toDate: null, // Or "2019-12-25",
					  minWidth: 1080, // Or 400
					  maxWidth: null, // Or 8000
					  minHeight: null, // Or 400
					  maxHeight: null, // Or 8000
					  minWHRatio: null,
					  maxWHRatio: 1,
					  // WHRatio = Width/Height ratio ( ==1 : Squared Photo,   < 1 : Portraited Photo, > 1 : Landscaped Photo)
				  },
				  showWidth: 1080, // These values will be used for quality of downloaded photos to show. real size to show in your MagicMirror region is recommended.
				  showHeight: 1920,
				  timeFormat: "YYYY/MM/DD HH:mm", // Or `relative` can be used.
			}
		},

# CSS File 
  
#GPHOTO_INFO {
    display:none;
  }

**Comment by hermanho** [comment]
Please try with this config:
```
minWHRatio: 1,
maxWHRatio: null,
```
