### ISSUE TITLE
REQUEST: Method to change folder on the fly (MQTT?)

### ISSUE THREAD

**Issue by Dropbear67** [aneaville/MMM-GooglePhotos#179]
I absolutely love MMM-GooglePhotos and use it on two frames, however one thing which would really finish it off for me would be a way to dynamically be able to change the current Google Photos folder being shown without having to stop and start the MM software.

PicFrame is another piece of software which does digital frames and it uses MQTT broker to be able to pass through a directory to change to - this really works well and enables integration with Home Assistant.   Enabling something similar on MMM-GooglePhotos would be the icing on the cake for me.

**Comment by hermanho** [comment]
Do you means the changing of config.albums in Configuration (~/MagicMirror/config/config.js) without restart MM?

**Comment by Dropbear67** [comment]
hello yes exactly. To be able to change the current album being displayed without having to restart MM

**Comment by hermanho** [comment]
There is nothing I can do. This is how it works in MM. Otherwise, the album list has to be put in another way but it is another story.

**Comment by smiles3983** [comment]
Maybe add a wildcard to the album names?  then if we want another album pulled, we just make sure it has the same substring.  like all albums that end with _MM. or something.  "*_MM".

**Comment by hermanho** [comment]
Added in v2.1.5
