### ISSUE TITLE
Stuck on Loading after refreshed install. 

### ISSUE THREAD

**Issue by alexsquared** [aneaville/MMM-GooglePhotos#196]
I've used this module for years with no issue.   recently, MM broke during an update so I had to do a fresh install.   I loaded a fresh SD card, installed the new OS, installed MM using the script, then began copying over my config files and module files.    I have two modules left to get working, with one being MMM-GooglePhotos.   It is just stuck on "Loading" for days.    At first I had an invalid credentials error, so I downloaded a new credentials file from the Google API tool and had it create the new json needed.    This resolved that issue but I still have this loading error.   I have also gone into the API window to confirm the API is published.   I can confirm that for publishing status it says "In Production." Any help would be greatly appreciated. If you want me to gather info from log files, please help me know the path to navigate to get those.

**Comment by hermanho** [comment]
Please copy the logging from the terminal when you execute `npm start`

**Comment by alexsquared** [comment]
> Please copy the logging from the terminal when you execute `npm start`

Do I need to stop the MM and then restart, or just open a terminal and click npm start?  Does it matter that I'm using pm2 instead of npm?

**Comment by hermanho** [comment]
> > Please copy the logging from the terminal when you execute `npm start`
> 
> Do I need to stop the MM and then restart, or just open a terminal and click npm start? Does it matter that I'm using pm2 instead of npm?

You can run `pm2 logs <id / name>` to check the process logs location. Then you can view the error in the log file.

**Comment by alexsquared** [comment]
what would I use as the id/name?

**Comment by hermanho** [comment]
> what would I use as the id/name?

You can check in `pm2 list`. Usually it is `0`.

**Comment by alexsquared** [comment]
interesting.  It's saying it can't find my album.

**Comment by alexsquared** [comment]
I'm confused by this error as I used the same API as previously.    I just published a new credential set and created the json with it.

**Comment by alexsquared** [comment]
is there a way to verify in a browser that it is accessing the correct account?

**Comment by alexsquared** [comment]
actually just solved this.  I logged into the google account and for some reason the album was not longer shared.   I reshared the account and now it is working again.  Thank you so much!
